__author__ = 'karlp'

STLINK_CMD_SIZE_V2          = 16

STLINK_GET_VERSION             = 0xF1
STLINK_DEBUG_COMMAND           = 0xF2
STLINK_DFU_COMMAND             = 0xF3
STLINK_SWIM_COMMAND            = 0xF4
STLINK_GET_CURRENT_MODE        = 0xF5
STLINK_GET_TARGET_VOLTAGE      = 0xF7

STLINK_MODE_DFU = 0
STLINK_MODE_MASS = 1
STLINK_MODE_DEBUG = 2
STLINK_MODE_SWIM = 3
STLINK_MODE_BOOTLOADER = 4

STLINK_DFU_EXIT = 0x7

STLINK_DEBUG_STATUS                = 0x01
STLINK_DEBUG_RESETSYS              = 0x03 # apiv1 from stlink-texane?!
STLINK_DEBUG_READMEM32             = 0x07
STLINK_DEBUG_WRITEMEM32            = 0x08
STLINK_DEBUG_RUNCORE               = 0x09
STLINK_DEBUG_ENTER_SWD             = 0xa3
STLINK_DEBUG_APIV2_ENTER           = 0x30
STLINK_DEBUG_APIV2_RESETSYS        = 0x32
STLINK_DEBUG_APIV2_READREG         = 0x33
STLINK_DEBUG_APIV2_WRITEREG        = 0x34
STLINK_DEBUG_APIV2_WRITEDEBUGREG   = 0x35
STLINK_DEBUG_APIV2_READDEBUGREG    = 0x36
STLINK_DEBUG_UNKNOWN_MAYBE_SYNC    = 0x3e
STLINK_DEBUG_EXIT                  = 0x21
STLINK_DEBUG_APIV2_START_TRACE_RX  = 0x40
STLINK_DEBUG_APIV2_STOP_TRACE_RX   = 0x41
STLINK_DEBUG_APIV2_GET_TRACE_NB    = 0x42
